SELECT F.CAR_ID, F.AVERAGE_DURATION
FROM (
    SELECT ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION, C.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    GROUP BY C.CAR_ID
) AS F
WHERE F.AVERAGE_DURATION >= 7
ORDER BY F.AVERAGE_DURATION DESC, F.CAR_ID DESC